# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-02 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wolframalpha_key', models.CharField(default='', max_length=200, null=True)),
                ('email_host', models.CharField(default='', max_length=200, null=True)),
                ('email_host_password', models.CharField(default='', max_length=200, null=True)),
                ('email_host_user', models.CharField(default='', max_length=200, null=True)),
                ('server_notifier', models.CharField(default='', max_length=200, null=True)),
                ('secret_key', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
    ]
