# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-02 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Key',
        ),
    ]
